### ISSUE TITLE
Search Widget: Add date range picker

### ISSUE THREAD

**Issue by saumier** [culturecreates/minimal-footlight-search-widget#1]
As a visitor to the front-end calendar of Tout Culture, I can select a date or date range to filter my search for events. The calendar can switch between english and french using a data-language parameter in the html page that loads the overall search widget.

For the first version please use the layout that comes with the NPM package, and only set colour scheme from Minimal's Figma.

Flash Yellow #FFF649 and Light Yellow #F2EB9F

### Test Cases

Date range
1. By default there is no date displayed in the search bar - only a date picker icon in the extreme right of the search bar.
3. Click the date picker icon --> date picker widget opens, current date is highlighted.
4. Click the date of upcoming Monday --> Monday is marked
5. Click the date of following Friday --> The date range is marked, the date picker closes, the search bar displays the date range  DD MMM YY - DD MMM YY (example 20 FEV 23 - 24 FEV 23), the event drop-down displays events according to the date range, the search field is in focus.
6. Click the date range string or icon in the search bar --> date picker opens displaying the date range, and the events dropdown remains open.

Single Date
1. Prerequisite: Starting with a date range already selected and the focus in the search field.
1. Click the date range text or icon --> Date picker opens and events dropdown remains open.
2. Click the checkbox "Rechercher à une date précise" --> the current date is highlighted, the date range in the search field is unchanged.
3. Click Friday --> the date is marked, the date picker closes, the search bar displays the date  DD MMM YY (example 24 FEV 23), the event drop-down displays events according to the start date (the selected date), the search field is in focus.
4. Click the date or icon in the search bar --> date picker opens displaying the selected date and the checkbox  "Rechercher à une date précise" has remained selected, and events dropdown remains open.
5. Uncheck the checkbox --> current date is highlighted, the date in the search field is unchanged.

### Screen Design

![Image](https://user-images.githubusercontent.com/419491/216977052-4e29c411-37ac-4483-afb5-8d4c30de7a30.png)

**Comment by saumier** [comment]
@AbhishekPAnil Here is a React Calendar that I found but have never used. You can take a look. If you find a better one let me know. https://projects.wojtekmaj.pl/react-calendar/

**Comment by AbhishekPAnil** [comment]
@saumier https://projects.wojtekmaj.pl/react-calendar/----> provides an option to switch to between single date and date range .

**(ignore the check box at the bottom)**-----> This will restrict the user to enter only a particular type of date (either single or date range).

Do we want to do only a single date or date range for the first pass or do we need to provide an option for the user to switch between date range and single date ?If yes,which one should be implemented?

 What are your thoughts on this? I just wanted to confirm before starting the implementation .Thank you .

**Comment by saumier** [comment]
@AbhishekPAnil Thanks for this first pass. It helped @troughc and I to try it out and discuss different options.  We decided that we should implement the checkbox as in the Figma. 

By default, the checkbox is unchecked and the widget is date range. When the checkbox is checked, the widget switches to single date.  

The display of the dates in the top search bar should be strings and a calendar icon as in the Figma. By default there is no date displayed. For single date, there is only a single date displayed in the search bar. For date range, there is a start date and end date displayed in the search bar.  If the user clicks anywhere on the date field or icon in the top search bar, the calendar widget appears, but there are no interactive widgets inside the top search bar. 

I will add some test cases in the description of this issue for testing.

**Comment by AbhishekPAnil** [comment]
@saumier Could you also add the figma link .Thanks.

**Comment by saumier** [comment]
@troughc Please review my test cases.

**Comment by troughc** [comment]
@saumier done, reviewed.

**Comment by saumier** [comment]
@AbhishekPAnil I tried inviting you to Minimal's Figma. Let me know if it worked.

https://www.figma.com/file/WLcSzebIfw3kK5ZRzYkVkj/ToutCulture-UX?node-id=757%3A14447&t=xiYCVwkvFG4NiamT-1

**Comment by saumier** [comment]
Hi @AbhishekPAnil Caitlin and I looked at both versions.  Thanks for setting that up.  We would like you to continue the complete version with the checkbox as it looks very promising and matches the Figma.  Please check that the date picker gets displayed in a layer above the search drop down.
