### ISSUE TITLE
Minimal Search Widget - tweaks

### ISSUE THREAD

**Issue by saumier** [culturecreates/minimal-footlight-search-widget#2]
- [x] Hide date picker when organization tab is selected
- [x] Feature to hide tabs without results
- [x] French labels
- [x] Remove images from Org list
- [x] Add orgs data param for installing widget
- [ ] Clear search when an event/org is selected from dropdown
- [ ] Clear dates with delete

**Comment by saumier** [comment]
@troughc Please test here http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com.  The only thing I haven't worked on is the mobile version.

**Comment by troughc** [comment]
@saumier 
Test 1: tested voir tout and I am always shown 1 event regardless of how many I have or how I have filtered the search. It is this: http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com/events/search-events.html?
or this (Same event): http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com/events/search-events.html?start-date-range=2023-02-25

Related to this event: http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com/events/event-details.html?eventId=63d9837e809754006565d36f

Test 2: to look at organizations, I cannot - I am asked to sign in.
