### ISSUE TITLE
Search Widget issues

### ISSUE THREAD

**Issue by troughc** [culturecreates/minimal-footlight-search-widget#77]
Did some tests on Chrome in http://demo.tout-culture.s3-website.ca-central-1.amazonaws.com/ 
Here are 5 issues:
### Number of events on results page does not match number of results in search widget (using keyword)
1. In search widget field, type "danse". Stay in events tab. 
2. 'See all results' shows a count of 12. Click see all results
3. 15 events are displayed on the page (and only 8 have the Danse event type).
###Number of ogranizations on results page does not match number of results in search widget (using keyword)
1. In search widget field, type "association". go to the organizations tab (you can go first or after you enter the search)
2. 'See all results' shows a count of 4. Click see all results 
3. 5 organizations are displayed on the page. 
### Results don't match number in search widget when you search by date (in events)
1. In search widget field, enter August 23. Stay on the events tab. 
2. 'See all results' shows a count of 14. Click see all results
3. 22 results are displayed on the results page. 
4. Some of the results are workshops, for example Danse Créative (Parent-enfant). You can go into the CMS and see that the event type for this event is Atelier | Danse. A second example is "Danse en ligne". You can see the the event types for this one are Atelier | Danse and Cours. (cours is "course" in English)
6.  Go back to the search widget field, keep August 23 as your date. Go to the atelier (workshop) tab. 
7. 'See all results' shows a count of 8. Click see all results
8. 8 results are displayed, so it looks like this one is okay.
### total number of organizations doesn't match result number
1. 1. in the search widget show the organizations. See all results' shows a count of 48. Click see all results
2. 95-ish results are displayed on results page
### "Centre d'action culturelle de la MRC de Papineau" organization is showing an address
1. in the search widget show the organizations. the last one in the list "Centre d'action culturelle de la MRC de Papineau" displays an address
2. click "Centre d'action culturelle de la MRC de Papineau". There is no address on the results page.
### Clicking a tab twice displays a no results message
1. click any tab in the search widget (Events, Workshops, Organizations). results are displayed
2. Click the same tab again. The "no events available" messages appear in the widget

**Comment by SyamBabu-M** [comment]
@saumier I fixed the issue of "Clicking a tab twice displays a no results message" and pushed it to develop. In my local and in demo site (http://demo.staging-tout-culture.s3-website.ca-central-1.amazonaws.com/index.html) I am able to see the change. But in https://minimal-footlight-search-widget.s3.ca-central-1.amazonaws.com/v2/test-dist.html the issue still persists. Because of this, I haven't updated the production yet. Is this an issue with the bucket? if not I will look into what went wrong from my side.

**Comment by saumier** [comment]
@SyamBabu-M Is this still an issue?
